modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${file.jarVersion}"
displayName="Bongo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bongo"
updateJSONURL="https://assets.melanx.de/updates/bongo.json"
authors="noeppi_noeppi, Contributors: MelanX, LordGrimmauld"
description='''
It's a bingo mod.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.95,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1-2.1.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.17.1-2.0.22,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minemention"
    mandatory=false
    versionRange="[1.17.1-1.0.6,)"
    ordering="NONE"
    side="BOTH"