modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${file.jarVersion}"
displayName="Bongo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bongo"
updateJSONURL="https://assets.melanx.de/updates/bongo.json"
authors="noeppi_noeppi"
description='''
It's a bingo mod.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.62,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4.0.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.19-4.0.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minemention"
    mandatory=false
    versionRange="[1.19-2.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jei"
    mandatory=false
    versionRange="[11.0.0.206,)"
    ordering="NONE"
    side="BOTH"
